fix [AllureXunitTheory] attribute does not work with MemberData issue
TinkoffCreditSystems/Allure.XUnit pull request #15
Opened 2021-11-03 07:45 UTC by AzatKalim

#11

2021-11-03 07:53 UTC, vladar107 approved these changes, later dismissed

2021-11-08 12:09 UTC, neparij requested changes

2021-11-08 12:09 UTC, neparij commented on src/Allure.XUnit/AllureXunitTestCase.cs
> +                    assemblyName = assembly.Assembly.GetName().Name;
Брекеты добавь, пожалуйста. {}

2021-11-08 12:09 UTC, neparij commented on src/Allure.XUnit/AllureXunitTestCase.cs
> +                    foreach (var genericType in genericTypes)
Брекеты добавь, пожалуйста. {}

2021-11-08 13:36 UTC, neparij approved these changes

2021-11-08 14:04 UTC, merged